### ISSUE TITLE
Response Error 

### ISSUE THREAD

**Issue by sphtd** [deexno/checkmk-telegram-plus#5]
Hi, after click HELP i have an error

Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",90],["af.httprm",89,"-2829122135122531690",14]]\n25\n[["e",4,null,null,131]]\n'. 
Unable to get response.
Please double-check the cookie values and verify your network environment or google account.

**Comment by deexno** [comment]
Have you set up the API key for Google Bard? If so, have you used this function frequently lately? If yes, then google has tagged your account/API key as bot, and you have to create a new key using another account... I already had this because I used it too often in a short time. Unfortunately, this is the disadvantage of this unofficial, but free API.

**Comment by deexno** [comment]
So it seems that Google suppresses the further use after a few uses. I have tested it myself and now also have the problem after frequent use of Google Bard… So one solution should be to create a new key with a new account, but that is also only a temporary solution… I'm thinking about removing the AI function or upgrading it with OpenAI, which is unfortunately not free…

I am referring to the following entry which is still open: 
https://github.com/dsdanielpark/Bard-API/issues/155

**Comment by deexno** [comment]
I'm sorry to announce that this help function has now been removed as Google makes it difficult to use this unofficial API which makes it useless as it also causes some problems on some systems.... With an update, the function is no longer included and the issue is "solved". I am working on finding a better solution in the future if there is still interest in this AI function.

**Comment by sphtd** [comment]
Thanks mate!
