### ISSUE TITLE
AI setup not working

### ISSUE THREAD

**Issue by bili123** [deexno/checkmk-telegram-plus#6]
When trying to use the AI functions, I only get the message 
"It seems that your AI is not configured. Have you configured the AI as described in the documentation?".
So it seems to not see the ai section in the config.ini, but:

AI model and API key are set and show up in the ai section of the config.ini.

I tried to add single and double quotes in the config ini, just in case ..., but it didn't help.

Since Checkmk is running on a headless server, I tried the cookie value from an X11 forwarded Epiphany browser as well as from a regular Windows host, same results.

Everything else is working (great tool!), so I would exclude permission issues with the config.ini.

Any idea?

**Comment by deexno** [comment]
Hello, have you already used the bot a few times? Or did it already not work out of the box? I assume that you have done everything else correctly. On which system are you running everything with which Python version? I guess that Google disables this "function" because several people have this problem now... This is of course the difficulty when using free but not official APIs...

**Comment by deexno** [comment]
So it seems that Google suppresses the further use after a few uses. I have tested it myself and now also have the problem after frequent use of Google Bard… So one solution should be to create a new key with a new account, but that is also only a temporary solution… I'm thinking about removing the AI function or upgrading it with OpenAI, which is unfortunately not free…

I am referring to the following entry which is still open: 
https://github.com/dsdanielpark/Bard-API/issues/155

**Comment by deexno** [comment]
I'm sorry to announce that this help function has now been removed as Google makes it difficult to use this unofficial API which makes it useless as it also causes some problems on some systems.... With an update, the function is no longer included and the issue is "solved". I am working on finding a better solution in the future if there is still interest in this AI function. I hope you still like the bot, and if you have any new features you would like to see, please feel free to contact me. Thank you for your support and contribution to the CheckMK Telegram Plus Bot!
